### ISSUE TITLE
The example SRW2Shadow_example01.py can't run.

### ISSUE THREAD

**Issue by tyjisinap** [srio/shadow3#10]

**Comment by srio** [comment]
Yes, I know. It has been removed. In the future we will come back to combine srw and Shadow, but for the moment it is not ready. Please note that the official shadow3 repository has been moved to https://github.com/srio/shadow3   Here, the SRW stuff has been removed.

**Comment by tyjisinap** [comment]
Thank you! I want to raytrace ED-XAS beam line with a tapered undulator, and my question is How to generate such a source in shadow3?

**Comment by srio** [comment]
Taper undulator never existed in shadow. So, you have to approximate it with a geometrical source

**Comment by tyjisinap** [comment]
Thank you very much! Shadow3 is really a powerful software! 

 
From: Manuel Sanchez del Rio
Date: 2016-01-20 16:03
To: srio/shadow3
CC: Yajun Tong
Subject: Re: [shadow3] The example SRW2Shadow_example01.py can't run. (#10)
Taper undulator never existed in shadow. So, you have to approximate it with a geometrical source

**Comment by lucarebuffi** [comment]
Indeed. Then you should try ShadowOui......:D

**Comment by tyjisinap** [comment]
Yes, I have already used ShaodowOui,  it can give intensity plot derectly.  it's great, especialy, for the raytracing of bent crystal.  but I haven't found how to simulate the tapered undulator. is there an example about this? Thank you very much!

Yajun Tong

**Comment by lucarebuffi** [comment]
ShadowOui is basically a graphic user interface upon shadow3, even if it contains a lot of new features.
The kernel is shadow3, and you can simulate the tapered undulator in the same way: with a geometrical source.

**Comment by tyjisinap** [comment]
Thank you very much, I will try. and why ShadowOui's undulator source can't enter the k lambdaU and so on?
From: Luca Rebuffi
Date: 2016-01-20 21:51
To: srio/shadow3
CC: Yajun Tong
Subject: Re: [shadow3] The example SRW2Shadow_example01.py can't run. (#10)
ShadowOui is basically a graphic user interface upon shadow3, even if it contains a lot of new features.
The kernel is shadow3, and you can simulate the tapered undulator in the same way: with a geometrical source.

**Comment by srio** [comment]
K is automatically set to get the harmonic at the wanted energy. See example 13 in the Tutorials, and the formulas in the document: 

https://github.com/srio/ShadowOui-Tutorial/blob/master/tutorial_shadowoui.pdf

https://github.com/srio/ShadowOui-Tutorial/

**Comment by tyjisinap** [comment]
Thank you very much!
