### ISSUE TITLE
footprint plot in plotxy does not work with beam instance

### ISSUE THREAD

**Issue by maurov** [srio/shadow3#18]
@srio The footprint plot on the optical element does not work with the 'beam' instance, only via file.

This fails:
`Shadow.ShadowTools.plotxy(beam, 1, 2, nbins=101, nolost=2, title="Footprint", ref=0)`

This works:
`Shadow.ShadowTools.plotxy('mirr.01', 1, 2, nbins=101, nolost=2, title="Footprint", ref=0)`

This means that one is obliged to write files to look at the footprint.

@lucarebuffi it would be nice to have a 'footprint plot' tab in ShadowOui.

**Comment by lucarebuffi** [comment]
In ShadowOui is already implemented. You must choose the option "Mirror" or "All", in the "File to Write Out" combo box in the "Output" tab of the "Advanced Settings", and a new Tab "Footprint" will appear in the plotting area.
![screen shot 2016-03-14 at 16 54 48](https://cloud.githubusercontent.com/assets/6713598/13750374/7f0c40c6-ea05-11e5-9e76-6dba50d6fd28.png)
![screen shot 2016-03-14 at 16 56 03](https://cloud.githubusercontent.com/assets/6713598/13750447/c2cb1b02-ea05-11e5-9061-18769564bfa0.png)

**Comment by srio** [comment]
Yes, this is one of the problems in python/shadow3. It does not export mirr.xx but only star.xx. At the beginning we thought this was OK, but then we see that mirr.xx is very useful. We will see, but it requires work in the python API, which I did not write :(

However, Luca already implemented the footprint plot I see he's answering this at this very the same time...

**Comment by maurov** [comment]
OK, now is clear to me. Thanks for the tip!
