### ISSUE TITLE
Python 2 support broken

### ISSUE THREAD

**Issue by robnagler** [srio/shadow3#28]
882530f94ed3e419e114b12411ce941489da4369 is causing ShadowToolsPrivate.py to no longer run on Python 2. The [print usage](https://github.com/srio/shadow3/commit/882530f94ed3e419e114b12411ce941489da4369#diff-e304417f25a77e8b1f8ac168dc8b7cd7L1) needs this line at the top of the file put back in:

```
from __future__ import print_function
```

**Comment by srio** [comment]
Hi Rob, 
sorry about that! I put it back. 
(We do not use python2 anymore!)

**Comment by robnagler** [comment]
Thanks, @srio!  Unfortunately, many codes are still py2-only so we have to support it as the least common denominator. This probably means you'll have to leave __future__ in the code forever. Sorry for the hassle.
